[package]
name = "isasnips"
version = "0.1.0"
authors = ["Asta Halkjær From <andro.from@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
walkdir = "2"